### PR TITLE
fix: unstable test caused by tidb topos polling

### LINKED ISSUE #1164: Test failure for master branch
## Bug Report

https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true

```
2022/02/07 09:10:58 [Fx] STOP		github.com/pingcap/tidb-dashboard/pkg/pd.NewEtcdClient()
[338](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:338)
--- FAIL: TestUserSuite (0.05s)
[339](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:339)
    --- PASS: TestUserSuite/TestWithNotLoginUser (0.00s)
[340](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:340)
    --- FAIL: TestUserSuite/TestWithSQLLoginUser (0.00s)
[341](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:341)
        info_test.go:132: 
[342](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:342)
            	Error Trace:	info_test.go:132
[343](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:343)
            	            				info_test.go:93
[344](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:344)
            	Error:      	"Error #01: authenticate failed, cause: error.tidb.no_alive_tidb
[345](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:345)
            	            	" should have 0 item(s), but has 1
[346](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:346)
            	Test:       	TestUserSuite/TestWithSQLLoginUser
[347](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:347)
    --- FAIL: TestUserSuite/TestWithShareCodeAndWritePrivLoginUser (0.00s)
[348](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:348)
        info_test.go:132: 
[349](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:349)
            	Error Trace:	info_test.go:132
[350](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:350)
            	            				info_test.go:112
[351](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:351)
            	Error:      	"Error #01: authenticate failed, cause: error.tidb.no_alive_tidb
[352](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:352)
            	            	" should have 0 item(s), but has 1
[353](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:353)
            	Test:       	TestUserSuite/TestWithShareCodeAndWritePrivLoginUser
[354](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:354)
    --- FAIL: TestUserSuite/TestWithShareCodeLoginUser (0.00s)
[355](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:355)
        info_test.go:132: 
[356](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:356)
            	Error Trace:	info_test.go:132
[357](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:357)
            	            				info_test.go:101
[358](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:358)
            	Error:      	"Error #01: authenticate failed, cause: error.tidb.no_alive_tidb
[359](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:359)
            	            	" should have 0 item(s), but has 1
[360](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:360)
            	Test:       	TestUserSuite/TestWithShareCodeLoginUser
[361](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:361)
FAIL
[362](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:362)
[2022/02/07 09:10:58.668 +00:00] [WARN] [retry_interceptor.go:61] ["retrying of unary invoker failed"] [target=endpoint://client-a9a810df-5f3a-4a8c-8f60-7b6ca679253e/127.0.0.1:2379] [attempt=0] [error="rpc error: code = Unavailable desc = transport is closing"]
[363](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:363)
[2022/02/07 09:10:58.668 +00:00] [INFO] [dynamic_config_manager.go:188] ["Save dynamic config to etcd"] [json="{\"keyvisual\":{\"auto_collection_disabled\":false,\"policy\":\"db\",\"policy_kv_separator\":\"\"},\"profiling\":{\"auto_collection_targets\":null,\"auto_collection_duration_secs\":0,\"auto_collection_interval_secs\":0},\"sso\":{\"core_config\":{\"enabled\":false,\"client_id\":\"\",\"discovery_url\":\"\",\"is_read_only\":false},\"auth_url\":\"\",\"token_url\":\"\",\"user_info_url\":\"\",\"sign_out_url\":\"\"}}"]
[364](https://github.com/pingcap/tidb-dashboard/runs/5090532388?check_suite_focus=true#step:5:364)
coverage: 15.2% of statements in ./pkg/...
```

### PR DESCRIPTION
**Pull request by shhdgit**
closed #1164

We will meet the following situations if the request comes quickly.

```
TiDB Dashboard start -------------------------------- Started 
                                           |
                                           | Start to fetch tidb topos ------------------------------------------- Successed

-------------------------------------------------------------------- Here comes a request after tidb dashboard started (we always assume that there is no tidb instance available)
```

### CODE REVIEW

File: pkg/tidb/forwarder.go [hunk 1]
```diff
@@ -52,7 +52,10 @@ func (f *Forwarder) Start(ctx context.Context) error {
 	f.sqlPort = f.sqlProxy.port()
 	f.statusPort = f.statusProxy.port()
 
+	// update tidb endpoints at least once when start
+	_ = f.updateTiDBEndpoints()
 	go f.pollingForTiDB()
```
Comment (breeswish) [inline pkg/tidb/forwarder.go:57]: Hmm. I cannot understand the change actually.

The previous workflow is as follows:

1. go f.pollingForTiDB()
2. inside pollingForTiDB: for { ..
3. inside for: fetch a topology

The new workflow is as follows:

1. fetch a topology
2. go f.pollingForTiDB()

The only difference between the two is that, in the previous workflow the polling will be performed **after** the goroutine is started.

Comment (shhdgit) [reply pkg/tidb/forwarder.go:57]: I want to make sure that the topology was fetched in the fx start workflow before we ready to serve the dashboard services.

The key point is to get all required metadata or configuration stuff and then provide services. After that, we can continually update the config on demand.

Is there any better ideas? And should we do same thing to dynamic config manager?

Comment (shhdgit) [reply pkg/tidb/forwarder.go:57]: If we provide the service first and get the required configuration later. This doesn't seem to guarantee that the service is ready.

Comment (breeswish) [reply pkg/tidb/forwarder.go:57]: > If we provide the service first and get the required configuration later. This doesn't seem to guarantee that the service is ready.

Yes. Currently they only provides "eventual consistency". TiDB Dashboard has never ensured to be ready at the moment when server is started, as user will always access TiDB Dashboard at least after a short moment (e.g. as long as several seconds).

**Comment by breeswish** [comment]
The bad news is that the CI is still failing with "no tidb alive" :( The direction might not be correct.

**Comment by shhdgit** [comment]
> The bad news is that the CI is still failing with "no tidb alive" :( The direction might not be correct.

This is caused by the fxtest.App, which has been reversed. I'll investigate the problem later.

**Comment by shhdgit** [comment]
/cc @baurine @breeswish 
PTAL, thanks!

**Review by baurine — COMMENTED** [review]
lgtm

File: tests/util/mock_app.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+	*fxtest.App
+
+	tb fxtest.TB
+}
+
+func NewMockApp(tb fxtest.TB, tidbVersion string, c *config.Config, opts ...fx.Option) *App {
+	allOpts := make([]fx.Option, 0, len(opts)+1)
+	allOpts = append(allOpts,
+		apiserver.Modules,
+		fx.Supply(featureflag.NewRegistry(tidbVersion)),
```
Comment (breeswish) [inline tests/util/mock_app.go:27]: This seems tricky. Currently we remove it from the apiserver.Modules and then supply it later everywhere. It would be better if it behaves as "overwrite" instead.

File: pkg/apiserver/apiserver.go [hunk 3]
```diff
@@ -98,6 +98,45 @@ func (s *Service) IsRunning() bool {
 	return s.status.IsRunning()
 }
 
+var Modules = fx.Options(
+	fx.Provide(
+		newAPIHandlerEngine,
+		newClients,
+		dbstore.NewDBStore,
```
Comment (breeswish) [inline pkg/apiserver/apiserver.go:105]: In test scenarios you may like a memory local store instead. The memory sqlite is widely used in unit tests and it is reliable enough.
