### PR TITLE
Fix(ui): Fix statemtent list initial loading

### LINKED ISSUE #829: Fix statemtent list initial loading
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Jump back to statement list page from detail page

**What did you expect to see?**

Show the skeleton first, then show the table content

**What did you see instead?**

https://user-images.githubusercontent.com/1284531/102974343-51a2ac80-4539-11eb-8403-274d60bfa4a2.mp4

Show the empty table first, then show skeleton, finally show the table content

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

### PR DESCRIPTION
**Pull request by shhdgit**
close #829 

- Set the initial loading statement to true
- Fix initial loading statement when queryStatementList
- Hide loading when catch errors

### CODE REVIEW

File: ui/lib/apps/Statement/utils/useStatementTableController.ts [hunk 1]
```diff
@@ -213,7 +217,6 @@ export default function useStatementTableController(
       }
 
       if (allTimeRanges.length === 0) {
-        setLoadingStatements(false)
```
Comment (shhdgit) [inline ui/lib/apps/Statement/utils/useStatementTableController.ts:216]: I think it might be useless statement update when queryStatementList start.

File: ui/lib/apps/Statement/utils/useStatementTableController.ts [hunk 2]
```diff
@@ -112,7 +112,7 @@ export default function useStatementTableController(
     [queryOptions, allTimeRanges]
   )
 
-  const [loadingStatements, setLoadingStatements] = useState(false)
+  const [loadingStatements, setLoadingStatements] = useState(true)
```
Comment (baurine) [inline ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: I remember it was `true` before then I modified it to `false`, you can see the commit history to understand why it was changed.

Comment (baurine) [reply ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: image

Comment (shhdgit) [reply ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: Ok, I'll check it.

Comment (shhdgit) [reply ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: This is used in combination with cache item. Wow, almost made a mistake.

Comment (shhdgit) [reply ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: But I think the semantics of the previous code is not clear enough and may cause bug.

File: ui/lib/apps/Statement/utils/useStatementTableController.ts [hunk 3]
```diff
@@ -209,11 +213,11 @@ export default function useStatementTableController(
       const cacheItem = cacheMgr?.get(cacheKey)
       if (cacheItem) {
         setStatements(cacheItem)
+        setLoadingStatements(false)
```
Comment (shhdgit) [inline ui/lib/apps/Statement/utils/useStatementTableController.ts:216]: Fixed by this line.

File: ui/lib/apps/Statement/utils/useStatementTableController.ts (hunk 2 above)
Comment (baurine) [reply ui/lib/apps/Statement/utils/useStatementTableController.ts:115]: OK, I will have a test when I am free.

**Comment by baurine** [comment]
I will test it today.

**Review by baurine — APPROVED** [review]
LGTM
