### PR TITLE
tidb_client: improve behavior when no alive tidb instance

### LINKED ISSUE #899: Misleading log and incorrect connection when no TiDB is available
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Use TiDB Dashboard to log in when no TiDB is available (this can be simulated by either not opening a TiDB at all, or open a TiDB using `skipRegisterToDashboard`).

**What did you expect to see?**

1. Display nice error messages like No TiDB is alive.
2. Make no connection at all.

**What did you see instead?**

The error message is "Failed to connect to TiDB" which is misleading.

The logs shown that it is connecting to the TiDB Dashboard proxy endpoint (and then closed by the proxy because no endpoint is alive).

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master.

### PR DESCRIPTION
**Pull request by unbyte**
closes #899 

image

image

### CODE REVIEW

**Comment by unbyte** [comment]
/cc @breeswish @baurine 
PTAL

File: pkg/tidb/forwarder.go [hunk 1]
```diff
@@ -93,10 +92,8 @@ func (f *Forwarder) pollingForTiDB() {
 			return err
 		}, bo)
 		if err != nil {
-			if errorx.IsOfType(err, ErrNoAliveTiDB) {
```
Comment (breeswish) [inline pkg/tidb/forwarder.go:96]: This may mean that there is connection error to the PD. In this case TiDB can be still alive and I think there is no need to clear TiDB remotes.

File: pkg/tidb/forwarder.go [hunk 2]
```diff
@@ -118,6 +115,28 @@ func (f *Forwarder) pollingForTiDB() {
...
 
+func (f *Forwarder) resolveSqlAddr(override string) (string, error) {
+	if override != "" {
+		return override, nil
+	}
+	if f.sqlProxy.noAliveRemote.Load() {
+		log.Warn("Unable to resolve sql connection address since no alive TiDB instance")
+		return "", ErrNoAliveTiDB.NewWithNoMessage()
+	}
+	return fmt.Sprintf("127.0.0.1:%d", f.sqlPort), nil
```
Comment (breeswish) [inline pkg/tidb/forwarder.go:126]: These two functions seems to be too verbose. Is it possible to reduce some duplicates? For example, I believe it can be as simple as:

```golang
func (f *Forwarder) getEndpointAddr(port int) (string, error) {
    if f.sqlProxy.noAliveRemote.Load() {
        return "", ErrNoAliveTiDB.NewWithNoMessage()
    }
    return fmt.Sprintf("127.0.0.1:%d", port), nil
}
```

Note: I exclude the "override" logic because this is NOT a behaviour that a forwarder / proxyer / load balancer should have.

File: pkg/tidb/forwarder.go [hunk 3]
```diff
@@ -92,12 +91,7 @@ func (f *Forwarder) pollingForTiDB() {
 			allTiDB, err = topology.FetchTiDBTopology(bo.Context(), f.etcdClient)
 			return err
 		}, bo)
-		if err != nil {
-			if errorx.IsOfType(err, ErrNoAliveTiDB) {
-				f.sqlProxy.updateRemotes(nil)
-				f.statusProxy.updateRemotes(nil)
-			}
-		} else {
+		if err == nil {
```
Comment (unbyte) [inline pkg/tidb/forwarder.go:94]: `errorx.IsOfType(err, ErrNoAliveTiDB)` is a legacy code and is always false, so I simply remove entire `err != nil` block

File: pkg/tidb/forwarder.go [hunk 4]
```diff
@@ -118,6 +113,14 @@ func (f *Forwarder) pollingForTiDB() {
 	}
 }
 
+func (f *Forwarder) getEndpointAddr(port int) (string, error) {
+	if f.statusProxy.noAliveRemote.Load() {
+		log.Warn("Unable to resolve connection address since no alive TiDB instance")
```
Comment (breeswish) [inline pkg/tidb/forwarder.go:118]: @HunDunDM PTAL about this line to see whether it will affect PD cluster without TiDB.

**Review by breeswish — COMMENTED** [review]
The rest LGTM. /cc @shhdgit PTAL

**Comment by shhdgit** [comment]
LGTM.

File: pkg/tidb/proxy.go [hunk 5]
```diff
@@ -95,12 +98,32 @@ func (p *proxy) updateRemotes(remotes map[string]struct{}) {
 		}
 		return true
 	})
+	p.noAliveRemote.Store(false)
```
Comment (shhdgit) [inline pkg/tidb/proxy.go:101]: Sorry for the slow response, why would this state change here, we don't know if any of remotes are alive yet.

File: pkg/tidb/client.go [hunk 6]
```diff
@@ -111,7 +111,10 @@ func (c *Client) OpenSQLConn(user string, pass string) (*gorm.DB, error) {
 		if overrideEndpoint != "" {
 			addr = overrideEndpoint
 		} else {
-			addr = fmt.Sprintf("127.0.0.1:%d", c.forwarder.sqlPort)
+			var err error
+			if addr, err = c.forwarder.getEndpointAddr(c.forwarder.sqlPort); err != nil {
```
Comment (HunDunDM) [inline pkg/tidb/client.go:115]: how about `getSQLEndpointAddr`?

File: pkg/tidb/client.go [hunk 7]
```diff
@@ -158,10 +164,19 @@ func (c *Client) SendGetRequest(path string) ([]byte, error) {
 		if overrideEndpoint != "" {
 			addr = overrideEndpoint
 		} else {
-			addr = fmt.Sprintf("127.0.0.1:%d", c.forwarder.statusPort)
+			var err error
+			if addr, err = c.forwarder.getEndpointAddr(c.forwarder.statusPort); err != nil {
```
Comment (HunDunDM) [inline pkg/tidb/client.go:168]: how about `getStatusEndpointAddr`?

File: pkg/tidb/forwarder.go [hunk 8]
```diff
@@ -118,6 +113,14 @@ func (f *Forwarder) pollingForTiDB() {
 	}
 }
 
+func (f *Forwarder) getEndpointAddr(port int) (string, error) {
```
Comment (HunDunDM) [inline pkg/tidb/forwarder.go:116]: ditto

**Review by HunDunDM — APPROVED** [review]
rest LGTM
